# Build stage

# Common base
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 AS spire-base-windows
RUN mkdir c:\\spire\\bin
RUN mkdir c:\\spire\\data
WORKDIR C:/spire
CMD []

# SPIRE Server
FROM spire-base-windows AS spire-server-windows
ENTRYPOINT ["c:/spire/bin/spire-server.exe", "run"]
COPY bin/spire-server.exe C:/spire/bin/spire-server.exe

# SPIRE Agent
FROM spire-base-windows AS spire-agent-windows
ENTRYPOINT ["c:/spire/bin/spire-agent.exe", "run"]
COPY ./bin/spire-agent.exe C:/spire/bin/spire-agent.exe
COPY ./bin/k8s-sat.exe C:/spire/bin/k8s-sat.exe
COPY ./bin/keymanager-k8s.exe C:/spire/bin/keymanager-k8s.exe

