{{- if .Values.configmapEntry.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Values.configmapEntry.name}} 
data:
  entry.sh: {{ tpl (.Files.Get  .Values.configmapEntry.file) . | quote }}
{{- end }}