{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
subjects:
{{ toYaml .Values.clusterRoleBinding.subjects | indent 2}}
roleRef:
{{ toYaml .Values.clusterRoleBinding.roleref | indent 2}}
{{- end }}