{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
    - port: {{ .Values.healthService.port }}
      targetPort: {{ .Values.healthService.targetPort }}
      protocol: {{ .Values.healthService.protocol }}
      name: {{ .Values.healthService.name }}
  selector:
    app: {{ .Values.labels.app }}
{{- end }}