# Default values for spire-agent-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imageMain:
  name: spire-agent
  repository: 956994857092.dkr.ecr.us-east-2.amazonaws.com/spire-agent
  pullPolicy: Always
  tag: ""

imageInit:
  name: init
  repository: curlimages/curl
  pullPolicy: Always
  tag: latest
  command: ["/bin/sh","-c"]
  args: ["while [ $(curl -sw '%{http_code}' http://a679eead9cabe49d69aa711dee7f586f-77346261.us-east-2.elb.amazonaws.com:8080/live -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the webserver...'; done"]


imagePullSecrets: []

serviceAccount:
  create: true
  name: spire-agent


# lables
labels:
  app: spire-agent

#clusterRole
clusterRole:
  create: true
  name: spire-agent-cluster-role
  rules:
  - apiGroups: ["*"]
    resources: ["pods","nodes","nodes/proxy","secrets","tokenreviews"]
    verbs: ["get","list","create","delete","update"]

#clusterRoleBinding
clusterRoleBinding:
  create: true
  name: spire-agent-cluster-role-binding
  subjects:
  - kind: ServiceAccount
    name: spire-agent
    namespace: spire
  roleref:
    kind: ClusterRole
    name: spire-agent-cluster-role
    apiGroup: rbac.authorization.k8s.io

#service
service:
  enabled: true
  type: ClusterIP
  port: 9091
  targetPort: 9091
  protocol: TCP
  name: api

#Health Check
healthService:
  enabled: true
  port: 9090
  targetPort: 9090
  protocol: TCP
  name: health

#ingress Layer 7 certificate Loadbalancer
ingress:
  enabled: false

#configmapAgent
configmapAgent:
  name:  spire-agent
  enabled: true
  file: configmaps/agent.conf


#Volumes
volumes:
- name: spire-config
  configMap:
    name: spire-agent
- name: spire-agent-socket
  hostPath:
    path: /run/spire/sockets
    type: DirectoryOrCreate

#Volume-Mounts
volumeMounts:
- name: spire-config
  mountPath: /run/spire/config
  readOnly: true
- name: spire-agent-socket
  mountPath: /run/spire/sockets
  readOnly: false

#Resources 
resources:
  limits:
    memory: 1000Mi
    cpu: 500m
  requests:
    memory: 100Mi
    cpu: 100m
    

#HPA
autoscaling:
  enabled: false
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75
  minReplicas: 2
  maxReplicas: 5

nodeSelector: {}

tolerations: []

affinity: {}